version: "3"

services:
  zimbra:
    build: .
    hostname: ${HOSTNAME}
    environment:
      PASSWORD: ${PASSWORD}
    ports:
      - '25:25'
      - '465:465'
      - '443:443'
      - '8443:8443'
      - '7071:7071'
      - '5005:5005'
